version: '3.4'

services:
  todoapp:
    image: ${DOCKER_REGISTRY-}todoapp
    build:
      context: .
      dockerfile: ToDoApp/Dockerfile
    environment:
      - ConnectionString=Server=database;Database=TodoDB;User Id=SA;Password=p@ssw0rd1;
  database:
    image: mcr.microsoft.com/mssql/server
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=p@ssw0rd1
    ports: 
      - "1433:1433"
  migrator:
    build: ./DatabaseMigrator
    depends_on: 
      - database
    volumes:
      - ./DatabaseMigrator/Scripts/:/app/dbscripts/
